apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodapp2
  labels:
    app: prodapp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prodapp2
  template:
    metadata:
      labels:
        app: prodapp2
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
