apiVersion: apps/v1
kind: Deployment
metadata:
  name: stgapp1
  labels:
    app: stgapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stgapp1
  template:
    metadata:
      labels:
        app: stgapp1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
