apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service2
  namespace: argocd
spec:
  project: service2-project
  source:
    repoURL: https://github.com/sainarendrapanga04/service-gitops.git
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
