apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: service1-dev-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: devapp1
            path: apps/dev/app1
  template:
    metadata:
      name: '{{app}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sainarendrapanga04/service-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
